Created ViewModels and responseModel
VincentMoyo/CoolCurrencyDevelopmentPod pull request #1
Opened 2021-11-04 13:18 UTC by VincentMoyo

Created Development Pod for Crypto and Bitcoin ViewModel

2021-11-10 13:59 UTC, AbdullahNanaDVT requested changes

2021-11-10 13:59 UTC, AbdullahNanaDVT commented on CoolCurrencyDevelopmentPod/RepositoryModelFramework/CryptoAndMetalsRepositorys.swift
> +        let apiKeyQueryItem = URLQueryItem(name: "apikey", value: "4645E475-133C-458A-AA48-2EB70A347301")
You could use a Constants class for the API Key. Also, it shouldn't be committed.

2021-11-10 13:59 UTC, AbdullahNanaDVT commented on CoolCurrencyDevelopmentPod/RepositoryModelFramework/CryptoAndMetalsRepositorys.swift
> +                                           value: "lj7xeh4umkscma4cv84w4d67l26ic34hjo2r2ky7571560jv9b2zu331ta1p")
Same as above

2021-11-10 13:59 UTC, AbdullahNanaDVT commented on CoolCurrencyDevelopmentPod/RepositoryModelFramework/CryptoDatabaseRepository.swift
> +                print(value)
This can be deleted.

2021-11-11 04:51 UTC, bgouws requested changes

2021-11-11 04:51 UTC, bgouws commented on CoolCurrencyDevelopmentPod/ViewModelFramework/Constant.swift
> +public struct Constant {
This will still be available on your local repo, please don't commit.

2021-11-11 12:33 UTC, bgouws approved these changes

2021-11-11 12:47 UTC, merged